# Generated by Django 5.0.6 on 2024-06-09 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20240608_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issues.status'),
        ),
    ]
