# Generated by Django 5.0.6 on 2024-06-07 01:09

from django.db import migrations

def populate_status(apps, schemaeditor):
  entries = {
    "To do": "Issues to be done",
    "In progress": "Issues that are work in progress",
    "Done": "Issues that are done"
  }
  Status = apps.get_model("issues", "Status")
  for key, value in entries.items():
    status_obj = Status(name=key, description=value)
    status_obj.save()

def populate_priority(apps, schemaeditor):
  entries = {
    "Low": "Low priority",
    "Medium": "Medium priority",
    "High": "High priority"
  }
  Priority = apps.get_model("issues", "Priority")
  for key, value in entries.items():
    priority_obj = Priority(name=key, description=value)
    priority_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_status_name'),
    ]

    operations = [
      migrations.RunPython(populate_status),
      migrations.RunPython(populate_priority)
    ]