# Generated by Django 5.0.6 on 2024-06-07 01:09

from django.db import migrations

def populate_teams(apps, schemaeditor):
  entries = {
    "Alpha": "First team",
    "Bravo": "Second team",
    "Charlie": "Third team"
  }
  Team = apps.get_model("accounts", "Team")
  for key, value in entries.items():
    team_obj = Team(name=key, description=value)
    team_obj.save()

def populate_roles(apps, schemaeditor):
  entries = {
    "Developer": "Team members who execute the work defined in issues",
    "Scrum Master": "The team's coach",
    "Product Owner": "The person on the team who defines what is built"
  }
  Role = apps.get_model("accounts", "Role")
  for key, value in entries.items():
    role_obj = Role(name=key, description=value)
    role_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
      migrations.RunPython(populate_teams),
      migrations.RunPython(populate_roles)
    ]